### ISSUE TITLE
Saving sample times

### ISSUE THREAD

**Issue by drf5n** [Dlloydev/Wokwi-Chip-Scope#1]
I was experimenting with saving sample tiles in the diagram.json file,
and seem to be having problems configuring a 1ms sample time.

This example should vary from 50Hz down to 1Hz or 0Hz with a minimum pulse width of 2ms

https://wokwi.com/projects/364450416218731521

But with the 

It seems to sample and frequency count at (maybe 100us? and interpret it as 1ms?): 

<img width="516" alt="image" src="https://github.com/Dlloydev/Wokwi-Chip-Scope/assets/2236516/1a4a4a98-7488-4c9a-95c1-0680aa51d5c8">

If you click the scope and set the sample time to 1ms, it then works as expected:

<img width="497" alt="image" src="https://github.com/Dlloydev/Wokwi-Chip-Scope/assets/2236516/6a8cafb6-b9b9-4e40-a9e7-9bf0f6b3d31a">

The diagram.json is:

```cpp
{
  "version": 1,
  "author": "David Forrest",
  "editor": "wokwi",
  "parts": [
    { "type": "wokwi-arduino-uno", "id": "uno", "top": 13.44, "left": 25.39, "attrs": {} },
    {
      "type": "wokwi-slide-potentiometer",
      "id": "pot1",
      "top": 56.47,
      "left": -131.4,
      "rotate": 270,
      "attrs": { "travelLength": "30", "value": "512" }
    },
    {
      "type": "wokwi-led",
      "id": "led1",
      "top": -113.59,
      "left": 163,
      "attrs": { "color": "red" }
    },
    {
      "type": "wokwi-resistor",
      "id": "r1",
      "top": -27.48,
      "left": 159.27,
      "rotate": 90,
      "attrs": { "value": "1000" }
    },
    {
      "type": "chip-scope",
      "id": "chip-scope1",
      "top": -219.05,
      "left": -118.88,
      "attrs": {
        "sampleTimeUs": "0",
        "sampleTimeMs": "1",
        "triggerChannel": "0",
        "triggerMode": "1",
        "crtColor": "0",
        "trace0Color": "14",
        "trace1Color": "12",
        "trace2Color": "10",
        "trace3Color": "2"
      }
    }
  ],
  "connections": [
    [ "pot1:SIG", "uno:A0", "green", [ "v22.45", "h256.48" ] ],
    [ "pot1:VCC", "uno:5V", "red", [ "v37.38", "h212.27" ] ],
    [ "pot1:GND", "uno:GND.3", "black", [ "v-13.48", "h-31.15", "v271.79", "h240.43" ] ],
    [ "r1:2", "uno:9", "green", [ "h0" ] ],
    [ "r1:1", "led1:A", "green", [ "h0" ] ],
    [ "led1:C", "uno:GND.1", "green", [ "v74.88", "h-49.54" ] ],
    [ "r1:2", "chip-scope1:D0", "green", [ "h20.27", "v-235.27", "h-344.01", "v13.51" ] ]
  ],
  "dependencies": { "chip-scope": "github:Dlloydev/Wokwi-Chip-Scope@1.0.0" }
}
```

**Comment by Dlloydev** [comment]
In diagram.json, change the version to 1.0.7
`"dependencies": { "chip-scope": "github:Dlloydev/Wokwi-Chip-Scope@1.0.7" }`

Thanks for experimenting with the scope chip ... let me know if you'd like to see any new features or find any new issues. 

EDIT: 
If you'd like to make changes to the code, it can be found in the GitHub repo in the src folder and is called `main.c` You'll need to copy and rename to `scope.chip.c`  The scope json file is found in the parent folder and is called `chip.json` This needs to be copied and renamed to `scope.chip.json ` Now you can import these 2 files and then clear the dependencies in diagram.json so it becomes  `"dependencies": {  }` Cumbersome ... but now you can work with the source code derived from GitHub.

I also have it [here](https://wokwi.com/projects/359331973918199809) which is much easier.

**Comment by drf5n** [comment]
Cool.  That version works better.  I normally hunt your scope-chip down with a google search for "Wokwi scope" and I cut and pasted an old version.

I should have come to the source.

Maybe I should paste it into the AccelStepper example on https://docs.wokwi.com/parts/wokwi-stepper-motor#simulator-examples
